from publication import db

class Anutapura(db.Model):
  id = db.Column(db.Integer(), primary_key=True)
  tahun = db.Column(db.String(length=4), nullable=False)
  p_kepuasan_rawat_jalan = db.Column(db.Integer())
  p_kepuasan_rawat_inap = db.Column(db.Integer())
  j_tenaga_medis = db.Column(db.Integer())
  dokter_umum = db.Column(db.Integer())
  dokter_bedah = db.Column(db.Integer())
  dokter_gigi = db.Column(db.Integer())
  dokter_penyakit_dalam = db.Column(db.Integer())
  dokter_anak = db.Column(db.Integer())
  dokter_tht = db.Column(db.Integer())
  dokter_mata = db.Column(db.Integer())
  dokter_radiologi = db.Column(db.Integer())
  dokter_patologi = db.Column(db.Integer())
  dokter_anastesi = db.Column(db.Integer())
  dokter_syaraf = db.Column(db.Integer())
  dokter_rehab = db.Column(db.Integer())
  dokter_gizi = db.Column(db.Integer())
  j_tenaga_paramedis = db.Column(db.Integer())
  perawat_pelaksana = db.Column(db.Integer())
  apoteker = db.Column(db.Integer())
  perawat_gigi = db.Column(db.Integer())
  bidan = db.Column(db.Integer())
  ahli_gizi = db.Column(db.Integer())
  penata_radiologi = db.Column(db.Integer())
  perekam_medis = db.Column(db.Integer())
  asisten_apoteker = db.Column(db.Integer())
  sanitarian = db.Column(db.Integer())
  teknik_medis = db.Column(db.Integer())
  district_id = db.Column(db.Integer(), nullable=True)
