from publication import db

class Dprd(db.Model):
  id = db.Column(db.Integer(), primary_key=True)
  tahun = db.Column(db.String(length=4), nullable=False)
  # ---
  u1 = db.Column(db.Integer())
  u2 = db.Column(db.Integer())
  u3 = db.Column(db.Integer())
  u4 = db.Column(db.Integer())
  u5 = db.Column(db.Integer())
  u6 = db.Column(db.Integer())
  u7 = db.Column(db.Integer())
  u8 = db.Column(db.Integer())
  u9 = db.Column(db.Integer())
  u10 = db.Column(db.Integer())
  u11 = db.Column(db.Integer())
  u12 = db.Column(db.Integer())
  u13 = db.Column(db.Integer())
  u14 = db.Column(db.Integer())
  u15 = db.Column(db.Integer())
  u16 = db.Column(db.Integer())
  u17 = db.Column(db.Integer())
  u18 = db.Column(db.Integer())
  u19 = db.Column(db.Integer())
  u20 = db.Column(db.Integer())
  u21 = db.Column(db.Integer())
  u22 = db.Column(db.Integer())
  u23 = db.Column(db.Integer())
  u24 = db.Column(db.Integer())
  u25 = db.Column(db.Integer())
  u26 = db.Column(db.Integer())
  u27 = db.Column(db.Integer())
  u28 = db.Column(db.Integer())
  u29 = db.Column(db.Integer())
  u30 = db.Column(db.Integer())
  u31 = db.Column(db.Integer())
  u32 = db.Column(db.Integer())
  u33 = db.Column(db.Integer())
  u34 = db.Column(db.Integer())
  u35 = db.Column(db.Integer())
  u36 = db.Column(db.Integer())
  u37 = db.Column(db.Integer())
  u38 = db.Column(db.Integer())
  u39 = db.Column(db.Integer())
  u40 = db.Column(db.Integer())
  u41 = db.Column(db.Integer())
  u42 = db.Column(db.Integer())
  u43 = db.Column(db.Integer())
  u44 = db.Column(db.Integer())
  u45 = db.Column(db.Integer())
  # ---
  district_id = db.Column(db.Integer(), nullable=True)
