from publication import db

class PekerjaanUmum(db.Model):
  id = db.Column(db.Integer(), primary_key=True)
  tahun = db.Column(db.String(length=4), nullable=False)
  panjang_jalan_sk = db.Column(db.Integer())
  panjang_ruas_jalan = db.Column(db.Integer())
  mantap = db.Column(db.Integer())
  tidak_mantap = db.Column(db.Integer())
  panjang_jalan = db.Column(db.Integer())
  dibangun_jalan = db.Column(db.Integer())
  ditingkatkan_jalan = db.Column(db.Integer())
  direkontruksi_jalan = db.Column(db.Integer())
  dipelihara_jalan = db.Column(db.Integer())
  dalam_kondisi_mantap_jalan = db.Column(db.Integer())
  panjang_jembatan = db.Column(db.Integer())
  dibangun_jembatan = db.Column(db.Integer())
  diganti_jembatan = db.Column(db.Integer())
  direhabilitasi_jembatan = db.Column(db.Integer())
  dipelihara_jembatan = db.Column(db.Integer())
  panjang_jalan_permukaan = db.Column(db.Integer())
  jalan_negara = db.Column(db.Integer())
  aspal_negara = db.Column(db.Integer())
  kerikil_negara = db.Column(db.Integer())
  tanah_negara = db.Column(db.Integer())
  tidak_dirinci_negara = db.Column(db.Integer())
  jalan_provinsi = db.Column(db.Integer())
  aspal_provinsi = db.Column(db.Integer())
  kerikil_provinsi = db.Column(db.Integer())
  tanah_provinsi = db.Column(db.Integer())
  tidak_dirinci_provinsi = db.Column(db.Integer())
  jalan_kota = db.Column(db.Integer())
  aspal_kota = db.Column(db.Integer())
  kerikil_kota = db.Column(db.Integer())
  tanah_kota = db.Column(db.Integer())
  tidak_dirinci_kota = db.Column(db.Integer())
  panjang_jalan_kewenangan = db.Column(db.Integer())
  jalan_negara_kewenangan = db.Column(db.Integer())
  baik_negara = db.Column(db.Integer())
  sedang_negara = db.Column(db.Integer())
  rusak_negara = db.Column(db.Integer())
  rusak_berat_negara = db.Column(db.Integer())
  jalan_provinsi_kewenangan = db.Column(db.Integer())
  baik_provinsi = db.Column(db.Integer())
  sedang_provinsi = db.Column(db.Integer())
  rusak_provinsi = db.Column(db.Integer())
  rusak_berat_provinsi = db.Column(db.Integer())
  jalan_kota_kewenangan = db.Column(db.Integer())
  baik_kota = db.Column(db.Integer())
  sedang_kota = db.Column(db.Integer())
  rusak_kota = db.Column(db.Integer())
  rusak_berat_kota = db.Column(db.Integer())
  district_id = db.Column(db.Integer(), nullable=True)
