# from publication import db

# class Inspektorat(db.Model):
#   id = db.Column(db.Integer(), primary_key=True)
#   tahun = db.Column(db.String(length=4), nullable=False)
#   ipp = db.Column(db.Integer())
#   ikid = db.Column(db.Integer())
#   p_tindak_lanjut = db.Column(db.Integer())
#   j_tindak_lanjut = db.Column(db.Integer())
#   j_total_temuan = db.Column(db.Integer())
#   p_pelanggaran_pegawai = db.Column(db.Float())
#   j_asn_sanksi = db.Column(db.Integer())
#   j_asn = db.Column(db.Integer())
#   j_temuan_bpk = db.Column(db.Integer())
#   j_wajib_lapor = db.Column(db.Integer())
#   lhkpn = db.Column(db.Integer())
#   lhkasn = db.Column(db.Integer())
#   p_kepatuhan_lhkpn = db.Column(db.Integer())
#   wl_melapor_lhkpn = db.Column(db.Integer())
#   wl_lhkpn = db.Column(db.Integer())
#   p_kepatuhan_lhkasn = db.Column(db.Integer())
#   wl_melapor_lhkasn = db.Column(db.Integer())
#   wl_lhksn = db.Column(db.Integer())
#   j_pengaduan_masyarakat = db.Column(db.Integer())
#   j_pengaduan_lanjut = db.Column(db.Integer())
#   district_id = db.Column(db.Integer(), nullable=True)
